# Generated by Django 3.0.5 on 2020-04-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vk_id', models.CharField(max_length=50, verbose_name='ключ вк')),
                ('tg_id', models.CharField(max_length=50, verbose_name='ключ телеграм')),
                ('site_id', models.CharField(max_length=50, verbose_name='ключ пользователя с сайта')),
                ('token', models.CharField(max_length=100, verbose_name='токен')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('category', models.CharField(choices=[('продукты', 'Продукты'), ('развлечения', 'Развлечения'), ('бытовые', 'Бытовые'), ('здоровье', 'Здоровье'), ('транспорт', 'Транспорт'), ('животные', 'Животные')], max_length=50, verbose_name='категория траты')),
                ('name', models.CharField(max_length=100, verbose_name='наименование траты')),
                ('sum', models.IntegerField(verbose_name='сумма траты')),
                ('common', models.BooleanField(default=False, verbose_name='является ли расход общим в семье')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spends', to='dbapi.DbUser', verbose_name='пользователь')),
            ],
        ),
    ]
