# Generated by Django 3.0.5 on 2020-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbuser',
            name='site_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ключ пользователя с сайта'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ключ телеграм'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, verbose_name='токен'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='vk_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ключ вк'),
        ),
    ]
