# Generated by Django 3.0.5 on 2020-04-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0002_auto_20200418_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('продукты', 'Продукты'), ('развлечения', 'Развлечения'), ('бытовые', 'Бытовые'), ('здоровье', 'Здоровье'), ('транспорт', 'Транспорт'), ('животные', 'Животные'), ('другое', 'Другое')], max_length=50, verbose_name='категория траты'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата'),
        ),
    ]
