# Generated by Django 3.0.5 on 2020-04-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_auto_20200422_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(max_length=50, verbose_name='категория траты'),
        ),
    ]
