# Generated by Django 3.0.5 on 2020-04-27 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0005_auto_20200426_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата')),
                ('name', models.CharField(max_length=100, verbose_name='источник дохода')),
                ('sum', models.IntegerField(verbose_name='сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='dbapi.DbUser', verbose_name='пользователь')),
            ],
        ),
    ]
