# Generated by Django 3.0.5 on 2020-04-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0007_auto_20200428_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='категория траты')),
                ('sum', models.IntegerField(verbose_name='сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitations', to='dbapi.DbUser', verbose_name='пользователь')),
            ],
        ),
    ]
